using System;

//<auto-generated/>
namespace CuroSettings
{
    public enum SettingsEnum
    { 
        Undefined = 0,
        FrameRate = 1,
        VSync = 2,
        MasterVolume = 3,
        AmbienceVolume = 4,
        SFXVolume = 5,
        MusicVolume = 6,
        Language = 7,
        FullscreenMode = 8,
        UIScale = 9,
        CameraRotationSensitivity = 10,
        CameraMovementSensitivity = 11,
        CameraZoomSensetiviy = 12,
        EnableDamageIndicators = 13,
        CameraDragSensitivity = 14,
        PostProcessingEnabled = 15,
        ShadowsEnabled = 16,
        FullTagsEnabled = 17,
        SpeedUpTimeScale = 18,
    }
}