
using System;

//<auto-generated/>
namespace CuroSettings
{
    public enum SettingsEnum
    { 
        Undefined,
                FrameRate,
        VSync,
        MasterVolume,
        AmbienceVolume,
        SFXVolume,
        MusicVolume,
        Language,
        FullscreenMode,
        UIScale,
        CameraRotationSensitivity,
        CameraMovementSensitivity,
        CameraZoomSensetiviy,

    }
}