
using System;

//<auto-generated/>
namespace CuroAudio
{
    public enum AudioEnum
    { 
        Undefined,
                music_ui_main_menu,
        music_game_wave,
        sound_ui_button_hover,
        sound_ui_button_click,

    }
}