using System;

//<auto-generated/>
namespace CuroAudio
{
    public enum AudioEnum
    { 
        Undefined = 0,
        music_ui_main_menu = 1,
        music_game_wave = 2,
        sound_ui_button_hover = 3,
        sound_ui_button_click = 4,
        sound_general_gameplay_placement = 5,
        sound_general_gameplay_building_selection_complete = 6,
        sound_general_gameplay_building_upgrade_selection_complete = 7,
        sound_enemy_death = 8,
        sound_enemy_exploder_death = 9,
        sound_combat_launch_projectile = 10,
        sound_combat_shield_break = 11,
        sound_enviroment_vegetation_hover = 12,
        sound_enviroment_rocks_hover = 13,
        ambience_evniroment_sea = 14,
        ambience_weather_rain = 15,
    }
}