using CuroCodeGen;
using UnityEngine;
using System;

#if UNITY_EDITOR
using System.Threading.Tasks;
using UnityEditor;
#endif

#if UNITY_EDITOR

namespace CuroAudio
{
    [CustomEditor(typeof(AudioSystemConfig))] 
    public sealed class AudioReferenceContainerEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            AudioSystemConfig audioContainer = (AudioSystemConfig)target;
            
            if (GUILayout.Button("Regenerate enum"))
            {
                if (audioContainer.CheckForDuplicateIDs())
                {
                    Debug.LogError("Found duplicate IDs, cannot regenerate AudioEnum");
                    return;
                }
                
                Debug.Log("No duplicates found");
                
                ScriptFileGenerator.Generate(typeof(AudioEnumGenerator));
                
                Debug.Log("Enum generated successfully");
                
                audioContainer.ApplyEnumValues();
                
                Debug.Log("Enum values applied correctly");
            }

            if (GUILayout.Button("ApplyEnumValues"))
            {
                audioContainer.ApplyEnumValues();
                
                Debug.Log("Enum values applied correctly");
            }
            
            DrawDefaultInspector();
        }

        private async Task WaitForCompilationToEnd()
        {
            while (!EditorApplication.isCompiling)
            {
                Debug.Log("Waiting for compilation to start");

                await Task.Yield();
            }
            
            while (!EditorApplication.isCompiling)
            {
                Debug.Log("Waiting for compilation to start");
            }
        }
    }
    
    [Generator] public sealed class AudioEnumGenerator : ICodeGenerator
    {
        private const string GeneratedFileBlueprint = @"
using System;

//<auto-generated/>
namespace CuroAudio
{
    public enum AudioEnum
    { 
        Undefined,
        #
    }
}";
        private const string GeneratedEnumEntryBlueprint = @"        #,
";
        
        public void Execute(GeneratorContext context)
        {
            AudioSystemConfig container = Resources.Load<AudioSystemConfig>("Audio/AudioMainContainer");

            string generatedFileCode = string.Empty;
            
            container.Sectors.ForEach(sector =>
            {
                sector.SubSectors.ForEach(subSector =>
                {
                    for (int i = 0; i < subSector.AudioReferenceEntries.Count; i++)
                    {
                        string enumStringValue = AudioUtility.GetAudioReferenceFullID(sector.Name, subSector.Name, subSector.AudioReferenceEntries[i].SoundID);

                        generatedFileCode += GeneratedEnumEntryBlueprint.Replace("#", enumStringValue);
                    }
                });
            });

            string resultFileCode = GeneratedFileBlueprint.Replace("#", generatedFileCode);
            
            context.SetFolderPath(AudioUtility.GENERATED_CODE_PATH);
            context.AddCode("AudioEnum.Generated.cs", resultFileCode);
        }
    }
}

#endif