using UnityEngine;

#if UNITY_EDITOR
using System;
using System.IO;
using CuroCodeGen;
using UnityEditor;
#endif

#if UNITY_EDITOR

namespace CuroAudio
{
    [CustomEditor(typeof(AudioSystemConfig))] 
    public sealed class AudioReferenceContainerEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            AudioSystemConfig audioContainer = (AudioSystemConfig)target;
            
            if (GUILayout.Button("Regenerate enum"))
            {
                if (audioContainer.CheckForDuplicateIDs())
                {
                    Debug.LogError("Found duplicate IDs, cannot regenerate AudioEnum");
                    return;
                }
                
                Debug.Log("No duplicates found");
                
                ScriptFileGenerator.Generate(typeof(AudioEnumGenerator));
                
                Debug.Log("Enum generated successfully");
            }

            if (GUILayout.Button("ApplyEnumValues"))
            {
                audioContainer.ApplyEnumValues();
                
                Debug.Log("Enum values applied correctly");
            }
            
            DrawDefaultInspector();
        }
    }
    
    [Generator] public sealed class AudioEnumGenerator : ICodeGenerator
    {
        private const string FILE_NAME = "AudioEnum.Generated.cs";
        private const string GeneratedFileBlueprintStart = @"using System;

//<auto-generated/>
namespace CuroAudio
{
    public enum AudioEnum
    { 
        Undefined = 0,";
        
        private const string GeneratedFileBlueprintEnd = @"    }
}";

        private const string GeneratedEnumEntryBlueprint = @"        %,
";
        
        public void Execute(GeneratorContext context)
        {
            AudioSystemConfig container = Resources.Load<AudioSystemConfig>("Audio/AudioMainContainer");
            string initialFileText = string.Empty;
            string fileText = Environment.NewLine;
            int itemIndex = 1;
            
            if (Directory.Exists(AudioUtility.GENERATED_CODE_PATH))
            {
                using StreamReader reader = new StreamReader(AudioUtility.GENERATED_CODE_PATH + $"/{FILE_NAME}");

                initialFileText = reader.ReadToEnd();

                initialFileText = initialFileText.Replace(GeneratedFileBlueprintStart, "");
                initialFileText = initialFileText.Replace(GeneratedFileBlueprintEnd, "");
            }
            
            container.Sectors.ForEach(sector =>
            {
                sector.SubSectors.ForEach(subSector =>
                {
                    for (int i = 0; i < subSector.AudioReferenceEntries.Count; i++)
                    {
                        string enumStringValue = AudioUtility.GetAudioReferenceFullID(sector.Name, subSector.Name, subSector.AudioReferenceEntries[i].SoundID);

                        string nextLine;
                        
                        if (initialFileText.Contains($"{enumStringValue} = "))
                        {
                            int startIndex = initialFileText.IndexOf($"{enumStringValue} = ");
                            int endIndex = initialFileText.IndexOf(',', startIndex);
                            
                            nextLine = initialFileText.Substring(startIndex, endIndex - startIndex);
                        }
                        else
                        {
                            nextLine = enumStringValue + $" = {GetFreeItemIndex()}"; 
                        }

                        fileText += GeneratedEnumEntryBlueprint.Replace("%", nextLine);
                    }
                });
            });

            string resultFileCode = GeneratedFileBlueprintStart + fileText + GeneratedFileBlueprintEnd;
            
            context.SetFolderPath(AudioUtility.GENERATED_CODE_PATH);
            context.AddCode(FILE_NAME, resultFileCode);
            
            return;

            int GetFreeItemIndex()
            {
                while (fileText.Contains(itemIndex.ToString()) || initialFileText.Contains(itemIndex.ToString()))
                {
                    itemIndex++;
                }
                
                return itemIndex;
            }
        }
    }
}

#endif