using UnityEngine;

#if UNITY_EDITOR
using CuroCodeGen;
using UnityEditor;
#endif

#if UNITY_EDITOR

namespace CuroSettings
{
    [CustomEditor(typeof(SettingsConfig))]
    public sealed class AudioReferenceContainerEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            SettingsConfig settingsConfig = (SettingsConfig)target;

            if (GUILayout.Button("Regenerate enum"))
            {
                if (settingsConfig.CheckForDuplicateSaveKeys())
                {
                    Debug.LogError("Found duplicate save keys, cannot regenerate SettingsEnum");
                    return;
                }

                Debug.Log("No duplicates found");

                ScriptFileGenerator.Generate(typeof(SettingsEnumGenerator));

                Debug.Log("Enum generated successfully");
            }

            if (GUILayout.Button("ApplyEnumValues"))
            {
                settingsConfig.ApplyEnumValues();

                Debug.Log("Enum values applied correctly");
            }

            DrawDefaultInspector();
        }
    }

    [Generator] public sealed class SettingsEnumGenerator : ICodeGenerator
    {
        private const string GeneratedFileBlueprint = @"
using System;

//<auto-generated/>
namespace CuroSettings
{
    public enum SettingsEnum
    { 
        Undefined,
        %
    }
}";
        private const string GeneratedEnumEntryBlueprint = @"        %,
";
        
        public void Execute(GeneratorContext context)
        {
            SettingsConfig settingsConfig = Resources.Load<SettingsConfig>("Settings/SettingsConfig");

            string generatedFileCode = string.Empty;
            
            settingsConfig.SettingConfigs.ForEach(config =>
            {
                generatedFileCode += GeneratedEnumEntryBlueprint.Replace("%", config.SaveKey);
            });

            string resultFileCode = GeneratedFileBlueprint.Replace("%", generatedFileCode);
            
            context.SetFolderPath("Assets/Scripts/Settings");
            context.AddCode("SettingEnum.Generated.cs", resultFileCode);
        }
    }
}

#endif