using UnityEngine;

#if UNITY_EDITOR
using System;
using System.IO;
using CuroCodeGen;
using UnityEditor;
#endif

#if UNITY_EDITOR

namespace CuroSettings
{
    [CustomEditor(typeof(SettingsConfig))]
    public sealed class SettingsConfigEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            SettingsConfig settingsConfig = (SettingsConfig)target;

            if (GUILayout.Button("Regenerate enum"))
            {
                if (settingsConfig.CheckForDuplicateSaveKeys())
                {
                    Debug.LogError("Found duplicate save keys, cannot regenerate SettingsEnum");
                    return;
                }

                Debug.Log("No duplicates found");

                ScriptFileGenerator.Generate(typeof(SettingsEnumGenerator));

                Debug.Log("Enum generated successfully");
            }

            if (GUILayout.Button("ApplyEnumValues"))
            {
                settingsConfig.ApplyEnumValues();

                Debug.Log("Enum values applied correctly");
            }

            DrawDefaultInspector();
        }
    }

    [Generator] public sealed class SettingsEnumGenerator : ICodeGenerator
    {
        private const string FILE_NAME = "SettingEnum.Generated.cs";
        private const string GeneratedFileBlueprintStart = @"using System;

//<auto-generated/>
namespace CuroSettings
{
    public enum SettingsEnum
    { 
        Undefined = 0,";
        
        private const string GeneratedFileBlueprintEnd = @"    }
}";

        private const string GeneratedEnumEntryBlueprint = @"        %,
";
        
        public void Execute(GeneratorContext context)
        {
            SettingsConfig settingsConfig = Resources.Load<SettingsConfig>("Settings/SettingsConfig");
            string initialFileText = string.Empty;
            string fileText = Environment.NewLine;
            int itemIndex = 1;
            
            if (Directory.Exists("Settings/SettingsConfig"))
            {
                using StreamReader reader = new StreamReader($"Assets/Scripts/Settings/{FILE_NAME}");

                initialFileText = reader.ReadToEnd();

                initialFileText = initialFileText.Replace(GeneratedFileBlueprintStart, "");
                initialFileText = initialFileText.Replace(GeneratedFileBlueprintEnd, "");
            }

            settingsConfig.SettingConfigs.ForEach(config =>
            {
                string saveKey = config.SaveKey;
                
                string nextLine;
                        
                if (initialFileText.Contains($"{saveKey} = "))
                {
                    int startIndex = initialFileText.IndexOf($"{saveKey} = ");
                    int endIndex = initialFileText.IndexOf(',', startIndex);
                            
                    nextLine = initialFileText.Substring(startIndex, endIndex - startIndex);
                }
                else
                {
                    nextLine = saveKey + $" = {GetFreeItemIndex()}"; 
                }

                fileText += GeneratedEnumEntryBlueprint.Replace("%", nextLine);
            });
            
            string resultFileCode = GeneratedFileBlueprintStart + fileText + GeneratedFileBlueprintEnd;
            
            context.SetFolderPath("Assets/Scripts/Settings");
            context.AddCode(FILE_NAME, resultFileCode);
                        
            return;

            int GetFreeItemIndex()
            {
                while (fileText.Contains(itemIndex.ToString()) || initialFileText.Contains(itemIndex.ToString()))
                {
                    itemIndex++;
                }
                
                return itemIndex;
            }
        }
    }
}

#endif